language: node_js
node_js:
  - "node"
install:
  - yarn
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - now --public --name yard-image-api --token $NOW_TOKEN && now alias --token $NOW_TOKEN
